/**
 * Represents the different states or "pages" of the application.
 * This enum controls which component is rendered as the main content.
 */
export enum AppState {
  /** The initial state where the user uploads their resumes. */
  UPLOAD = 'UPLOAD',
  /** The state where the user provides the job description. */
  JOB_DESCRIPTION = 'JOB_DESCRIPTION',
  /** The state shown while the initial resume draft is being generated. */
  GENERATING = 'GENERATING',
  /** The state where the user reviews, refines, and selects a resume draft. */
  REVIEW = 'REVIEW',
  /** The final state where the user can copy or export their completed resume. */
  FINAL = 'FINAL',
}

/**
 * Represents a source from Google Search used for grounding the AI's response.
 * This is used when incorporating "best resume practices."
 */
export type GroundingSource = {
    web: {
        /** The URL of the source article. */
        uri: string;
        /** The title of the source article. */
        title: string;
    }
};

/**
 * Represents a single resume draft generated by the AI.
 */
export type Draft = {
    /** The plain text content of the resume draft. */
    text: string;
    /** Optional array of web sources used to generate or refine this draft. */
    sources?: GroundingSource[];
    /** An optional log of changes made by the AI during a refinement step. */
    changelog?: string;
};